/**
 * @fileoverview gRPC-Web generated client stub for position
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v3.19.6
// source: position.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as position_pb from './position_pb';


export class PositionClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorStreaming = new grpcWeb.MethodDescriptor(
    '/position.Position/Streaming',
    grpcWeb.MethodType.SERVER_STREAMING,
    position_pb.PositionReq,
    position_pb.Point,
    (request: position_pb.PositionReq) => {
      return request.serializeBinary();
    },
    position_pb.Point.deserializeBinary
  );

  streaming(
    request: position_pb.PositionReq,
    metadata?: grpcWeb.Metadata): grpcWeb.ClientReadableStream<position_pb.Point> {
    return this.client_.serverStreaming(
      this.hostname_ +
        '/position.Position/Streaming',
      request,
      metadata || {},
      this.methodDescriptorStreaming);
  }

}

