/**
 * @fileoverview gRPC-Web generated client stub for unitcoords
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v3.19.6
// source: unit_coords.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as unit_coords_pb from './unit_coords_pb';


export class UnitCoordsClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorCoords = new grpcWeb.MethodDescriptor(
    '/unitcoords.UnitCoords/Coords',
    grpcWeb.MethodType.SERVER_STREAMING,
    unit_coords_pb.Unit,
    unit_coords_pb.Point,
    (request: unit_coords_pb.Unit) => {
      return request.serializeBinary();
    },
    unit_coords_pb.Point.deserializeBinary
  );

  coords(
    request: unit_coords_pb.Unit,
    metadata?: grpcWeb.Metadata): grpcWeb.ClientReadableStream<unit_coords_pb.Point> {
    return this.client_.serverStreaming(
      this.hostname_ +
        '/unitcoords.UnitCoords/Coords',
      request,
      metadata || {},
      this.methodDescriptorCoords);
  }

}

